# A simple example of ClusterConfig object with two nodegroups:
# one EKS managed nodegroup and one self-managed nodegroup
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-in-existing-vpc-eksctl    # cluster name
  region: us-east-1

managedNodeGroups:
  - name: managed-private-ng-1            # nodegroup name
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    subnets:
      - subnet-0ec6b6294581a075c          # subnet you want to put the nodes in

nodeGroups:
  - name: private-ng-2                    # nodegroup name
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    subnets:
      - subnet-0ec6b6294581a075c          # subnet you want to put the nodes in