AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloudformation template to create EKS readonly policy'

Resources:
  PolicyEksReadOnly:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: 'EKS read only access policy'
      ManagedPolicyName: 'EKSReadOnly'
      Path: '/'
      PolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Action: 
                - 'eks:ListNodegroups'
                - 'eks:DescribeFargateProfile'
                - 'eks:ListTagsForResource'
                - 'eks:ListAddons'
                - 'eks:DescribeAddon'
                - 'eks:ListFargateProfiles'
                - 'eks:DescribeNodegroup'
                - 'eks:DescribeIdentityProviderConfig'
                - 'eks:ListUpdates'
                - 'eks:DescribeUpdate'
                - 'eks:AccessKubernetesApi'
                - 'eks:DescribeCluster'
                - 'eks:ListClusters'
                - 'eks:DescribeAddonVersions'
                - 'eks:ListIdentityProviderConfigs'
            Resource: '*'